#!/bin/sh

# VXLAN setup
ip link add vxlan10 type vxlan id 10 dev eth0 dstport 4789
ip link set dev vxlan10 up
ip link add br0 type bridge
ip link set br0 up
brctl addif br0 eth0
brctl addif br0 vxlan10

vtysh << END
conf t
    no ipv6 forwarding
    
    ! add ip to interface and enable ospf on it
    interface eth1
        ip address 10.1.1.6/30
        ip ospf area 0
    exit
    interface lo
        ip address 1.1.1.3/32
        ip ospf area 0
    exit

    ! enable BGP with AS 1
    router bgp 1
        ! add RR as neighbor
        neighbor 1.1.1.1 remote-as 1

        ! communicate using loopback of RR
        neighbor 1.1.1.1 update-source lo

        address-family l2vpn evpn
            neighbor 1.1.1.1 activate
            advertise-all-vni
        exit-address-family
    exit

    ! enalble ospf routing
    router ospf
    exit

END