#!/bin/sh

vtysh << END
conf t
    no ipv6 forwarding

    interface eth0
        ip address 10.1.1.1/30
    exit
    interface eth1
        ip address 10.1.1.5/30
    exit
    interface eth2
        ip address 10.1.1.9/30
    exit

    ! if link like eth0-eth1 is down, the bgp link will be down too.
    ! we need a loopback to avoid this
    interface lo
        ip address 1.1.1.1/32
    exit

    router bgp 42
        neighbor belgium peer-group
        neighbor belgium remote-as 42
        neighbor belgium update-source lo

        ! add a trusted range of IPs for neighbors
        bgp listen range 1.1.1.0/29 peer-group belgium

        address-family l2vpn evpn
            neighbor belgium activate
            neighbor belgium route-reflector-client
        exit-address-family
    exit

    ! create a zone with leaf's and the spine (RR)
    router ospf
        network 0.0.0.0/0 area 0
    exit

END
